services:
  - type: web
    name: frontend-react
    runtime: static
    repo: https://github.com/SusieTsow/M324-Abschlussprojekt
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: frontend
  - type: web
    name: backend-express
    env: node
    repo: https://github.com/SusieTsow/M324-Abschlussprojekt
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 5001
version: "1"
