services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: MONGO_URI
        fromSecret: MONGO_URI
      - key: PORT
        value: "5001"

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: http://backend:5001
